modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "myplugin"
version = "${version}"
displayName = "Example Mod"
authors = "AUTHOR_NAME"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.myplugin]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.myplugin]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"